version: '3.8'

services:
  db:
    image: postgres:16
    container_name: exam-scan-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exams
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: exam-scan-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: exam-scan-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: exam-scan-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - api

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: exam-scan-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: exam-scan-prometheus
    restart: unless-stopped
    volumes:
      - ./backend/app/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: exam-scan-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  postgres_data:
  grafana_data:

networks:
  app-network:
    driver: bridge