FROM mcr.microsoft.com/vscode/devcontainers/python:3.13

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends postgresql-client git \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*