FROM mcr.microsoft.com/devcontainers/typescript-node:22

# Instala dependencias necesarias para el frontend
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends git \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*