apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090 # El nombre del servicio de Prometheus en docker-compose
    isDefault: true
    version: 1
    editable: true
